Machine.add("HSV.ck");
<<< "Adding HSV.ck" >>>;
Machine.add("class.sample.ck");
<<< "Adding sample class" >>>;
Machine.add("class.ks.ck");
Machine.add("class.ks-chord.ck");
<<< "Adding KS Chord" >>>;
Machine.add("ActionEnum.ck");
<<< "Adding ActionEnum.ck" >>>;
Machine.add("nameless-go.ck:" + me.arg(0));